spring:
  
  mongodb:
    uri: ${DB_URL}

  config:
    import: configserver:http://localhost:9090

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${SECURE_EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_SECRET}
          scope:
            - openid
            - profile
            - email

image:
  path: images/

PostImage:
  path: postImages/

OTP_EXPIRY_SECONDS: 200

secret:
  key: ${SECURE_KEY}

logging:
  level:
    com.user.service: DEBUG
    org.springframework.security.web.DEBUGFilterChainProxy: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.authorization: DEBUG
    org.springframework.security.access: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: TRACE

server:
  port: 8081
